version: "2"
services:
  node:
    image: "node:12"
    user: "root"
    working_dir: $PWD
    environment:
      - NODE_ENV=production
    volumes:
      - ./:$PWD
      - "/etc/localtime:/etc/localtime:ro"
    command: node index.js